<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMiTMxK4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMiTMxK4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMiTMxK4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMiTMxK4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMiTMxK4\App_KernelDevDebugContainer([
    'container.build_hash' => 'MiTMxK4',
    'container.build_id' => 'a8d8c493',
    'container.build_time' => 1619822409,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMiTMxK4');
