<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZMofHA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZMofHA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZMofHA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZMofHA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXZMofHA\App_KernelDevDebugContainer([
    'container.build_hash' => 'XZMofHA',
    'container.build_id' => '67665335',
    'container.build_time' => 1621368322,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZMofHA');
